import { Vector3 } from "three";
import { LegoBlockType } from "../../../Types/LegoBlockType";
import {
  plate_2_x_2_3022,
  plate_3023,
  slope_Brick_Inverted_2x2_3660,
  slope_Brick_Inverted_3665,
} from "../Set7722V1PartsImports";

export const steamLocomotive7722PostCarPhase3: LegoBlockType[] = [
  {
    partPath: plate_2_x_2_3022,
    partStartPosition: new Vector3(-265, 0, 180),
    partType: "3022",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.020",
    depends: [],
  },
  {
    partPath: plate_2_x_2_3022,
    partStartPosition: new Vector3(-290, 0, 180),
    partType: "3022",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.021",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_3665,
    partStartPosition: new Vector3(530, 0, 50),
    partType: "3665",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.012",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_3665,
    partStartPosition: new Vector3(550, 0, 50),
    partType: "3665",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.016",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_3665,
    partStartPosition: new Vector3(570, 0, 50),
    partType: "3665",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.014",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_3665,
    partStartPosition: new Vector3(590, 0, 50),
    partType: "3665",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.017",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_3665,
    partStartPosition: new Vector3(530, 0, 75),
    partType: "3665",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.015",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_3665,
    partStartPosition: new Vector3(550, 0, 75),
    partType: "3665",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.019",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_3665,
    partStartPosition: new Vector3(570, 0, 75),
    partType: "3665",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.018",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_3665,
    partStartPosition: new Vector3(590, 0, 75),
    partType: "3665",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.013",
    depends: [],
  },

  {
    partPath: plate_3023,
    partStartPosition: new Vector3(100, 0, 175),
    partType: "3023",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.026",
    depends: [],
  },
  {
    partPath: plate_3023,
    partStartPosition: new Vector3(120, 0, 175),
    partType: "3023",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.027",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_2x2_3660,
    partStartPosition: new Vector3(220, 0, 50),
    partType: "3660",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.022",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_2x2_3660,
    partStartPosition: new Vector3(245, 0, 50),
    partType: "3660",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.023",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_2x2_3660,
    partStartPosition: new Vector3(220, 0, 30),
    partType: "3660",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.024",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_2x2_3660,
    partStartPosition: new Vector3(245, 0, 30),
    partType: "3660",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.025",
    depends: [],
  },
];
