import { Vector3 } from "three";
import { LegoBlockType } from "../../../Types/LegoBlockType";
import { gate_1x4x2_Fence_3186 } from "../../../PartsImports/Gate_1x4x2_Fence_3186";
import { tile_1x8_4162 } from "../../../PartsImports/Tile_1x8_4162";
import { roundOpenStud_3062b } from "../../../PartsImports/RoundOpenStud_3062b";

export const platform4536Phase4: LegoBlockType[] = [
  {
    partPath: gate_1x4x2_Fence_3186,
    partStartPosition: new Vector3(-45, 0, 180),
    partType: "3186",
    materialId: "whitePlasticMaterial",
    slotId: "ModelMarker.015",
    depends: [],
  },
  {
    partPath: gate_1x4x2_Fence_3186,
    partStartPosition: new Vector3(-45, 0, 195),
    partType: "3186",
    materialId: "whitePlasticMaterial",
    slotId: "ModelMarker.016",
    depends: [],
  },
  {
    partPath: gate_1x4x2_Fence_3186,
    partStartPosition: new Vector3(-45, 0, 210),
    partType: "3186",
    materialId: "whitePlasticMaterial",
    slotId: "ModelMarker.017",
    depends: [],
  },
  {
    partPath: gate_1x4x2_Fence_3186,
    partStartPosition: new Vector3(-45, 0, 225),
    partType: "3186",
    materialId: "whitePlasticMaterial",
    slotId: "ModelMarker.018",
    depends: [],
  },
  {
    partPath: tile_1x8_4162,
    partStartPosition: new Vector3(25, 0, 180),
    partType: "4162",
    materialId: "whitePlasticMaterial",
    slotId: "ModelMarker.019",
    depends: [],
  },
  {
    partPath: tile_1x8_4162,
    partStartPosition: new Vector3(25, 0, 195),
    partType: "4162",
    materialId: "whitePlasticMaterial",
    slotId: "ModelMarker.020",
    depends: [],
  },

  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(110, 0, 140),
    partType: "3062b",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.021",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(125, 0, 140),
    partType: "3062b",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.022",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(140, 0, 140),
    partType: "3062b",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.023",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(155, 0, 140),
    partType: "3062b",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.024",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(170, 0, 140),
    partType: "3062b",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.025",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(185, 0, 140),
    partType: "3062b",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.026",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(110, 0, 155),
    partType: "3062b",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.027",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(125, 0, 155),
    partType: "3062b",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.028",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(140, 0, 155),
    partType: "3062b",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.029",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(155, 0, 155),
    partType: "3062b",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.030",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(170, 0, 155),
    partType: "3062b",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.031",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(185, 0, 155),
    partType: "3062b",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.032",
    depends: [],
  },

  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(110, 0, 170),
    partType: "3062b",
    materialId: "yellowPLasticMaterial",
    slotId: "ModelMarker.033",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(125, 0, 170),
    partType: "3062b",
    materialId: "yellowPLasticMaterial",
    slotId: "ModelMarker.034",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(140, 0, 170),
    partType: "3062b",
    materialId: "yellowPLasticMaterial",
    slotId: "ModelMarker.035",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(155, 0, 170),
    partType: "3062b",
    materialId: "yellowPLasticMaterial",
    slotId: "ModelMarker.036",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(170, 0, 170),
    partType: "3062b",
    materialId: "yellowPLasticMaterial",
    slotId: "ModelMarker.037",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(185, 0, 170),
    partType: "3062b",
    materialId: "yellowPLasticMaterial",
    slotId: "ModelMarker.038",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(110, 0, 185),
    partType: "3062b",
    materialId: "yellowPLasticMaterial",
    slotId: "ModelMarker.039",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(125, 0, 185),
    partType: "3062b",
    materialId: "yellowPLasticMaterial",
    slotId: "ModelMarker.040",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(140, 0, 185),
    partType: "3062b",
    materialId: "yellowPLasticMaterial",
    slotId: "ModelMarker.041",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(155, 0, 185),
    partType: "3062b",
    materialId: "yellowPLasticMaterial",
    slotId: "ModelMarker.042",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(170, 0, 185),
    partType: "3062b",
    materialId: "yellowPLasticMaterial",
    slotId: "ModelMarker.043",
    depends: [],
  },
  {
    partPath: roundOpenStud_3062b,
    partStartPosition: new Vector3(185, 0, 185),
    partType: "3062b",
    materialId: "yellowPLasticMaterial",
    slotId: "ModelMarker.044",
    depends: [],
  },
];
