import { Vector3 } from "three";
import { LegoBlockType } from "../../../Types/LegoBlockType";
import { technic_Brick_1x2_With_Pin_Hole_3700 } from "../../../PartsImports/Technic_Brick_1x2_With_Pin_Hole_3700";
import { technic_Axle_10_3737 } from "../../../PartsImports/Technic_Axle_10_3737";
import { technic_Bush_1_2_Type_II_Toothed_4265b } from "../../../PartsImports/Technic_Bush_1_2_Type_II_Toothed_4265b";
import { technic_Steering_Wheel_Small_3_Studs_Diameter_2819 } from "../../../PartsImports/Technic_Steering_Wheel_Small_3_Studs_Diameter_2819";
import { technic_Beam_4x05_LiftArm_with_Boss_2825 } from "../../../PartsImports/Technic_Beam_4x05_Liftarm_with_Boss_2825";

export const coalCart4564Phase9: LegoBlockType[] = [
  {
    partPath: technic_Brick_1x2_With_Pin_Hole_3700,
    partStartPosition: new Vector3(510, 0, 160),
    partType: "3040",
    materialId: "redPlasticMaterial",
    slotId: "ModelMarker.035",
    depends: [],
  },
  {
    partPath: technic_Axle_10_3737,
    partStartPosition: new Vector3(-50, 0, 680),
    partType: "3737",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.036",
    depends: ["ModelMarker.035"],
  },
  {
    partPath: technic_Bush_1_2_Type_II_Toothed_4265b,
    partStartPosition: new Vector3(-310, 0, 350),
    partType: "4265b",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.037",
    depends: ["ModelMarker.036"],
  },
  {
    partPath: technic_Steering_Wheel_Small_3_Studs_Diameter_2819,
    partStartPosition: new Vector3(-310, 0, 760),
    partType: "2819",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.038",
    depends: ["ModelMarker.037"],
  },
  //!!
  {
    partPath: technic_Beam_4x05_LiftArm_with_Boss_2825,
    partStartPosition: new Vector3(115, 0, 750),
    partType: "2825",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.039",
    depends: ["ModelMarker.036"],
  },
  {
    partPath: technic_Beam_4x05_LiftArm_with_Boss_2825,
    partStartPosition: new Vector3(130, 0, 750),
    partType: "2825",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.040",
    depends: ["ModelMarker.039"],
  },
  {
    partPath: technic_Beam_4x05_LiftArm_with_Boss_2825,
    partStartPosition: new Vector3(145, 0, 750),
    partType: "2825",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.041",
    depends: ["ModelMarker.040"],
  },
  {
    partPath: technic_Beam_4x05_LiftArm_with_Boss_2825,
    partStartPosition: new Vector3(160, 0, 750),
    partType: "2825",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.042",
    depends: ["ModelMarker.041"],
  },
  {
    partPath: technic_Beam_4x05_LiftArm_with_Boss_2825,
    partStartPosition: new Vector3(175, 0, 750),
    partType: "2825",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.043",
    depends: ["ModelMarker.042"],
  },
  {
    partPath: technic_Beam_4x05_LiftArm_with_Boss_2825,
    partStartPosition: new Vector3(190, 0, 750),
    partType: "2825",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.044",
    depends: ["ModelMarker.043"],
  },
  {
    partPath: technic_Beam_4x05_LiftArm_with_Boss_2825,
    partStartPosition: new Vector3(205, 0, 750),
    partType: "2825",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.045",
    depends: ["ModelMarker.044"],
  },
  {
    partPath: technic_Beam_4x05_LiftArm_with_Boss_2825,
    partStartPosition: new Vector3(220, 0, 750),
    partType: "2825",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.046",
    depends: ["ModelMarker.045"],
  },
  {
    partPath: technic_Beam_4x05_LiftArm_with_Boss_2825,
    partStartPosition: new Vector3(235, 0, 750),
    partType: "2825",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.047",
    depends: ["ModelMarker.046"],
  },
  {
    partPath: technic_Beam_4x05_LiftArm_with_Boss_2825,
    partStartPosition: new Vector3(250, 0, 750),
    partType: "2825",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.048",
    depends: ["ModelMarker.047"],
  },
  {
    partPath: technic_Beam_4x05_LiftArm_with_Boss_2825,
    partStartPosition: new Vector3(265, 0, 750),
    partType: "2825",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.049",
    depends: ["ModelMarker.048"],
  },
  {
    partPath: technic_Beam_4x05_LiftArm_with_Boss_2825,
    partStartPosition: new Vector3(280, 0, 750),
    partType: "2825",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.050",
    depends: ["ModelMarker.049"],
  },
  {
    partPath: technic_Brick_1x2_With_Pin_Hole_3700,
    partStartPosition: new Vector3(510, 0, 175),
    partType: "3040",
    materialId: "redPlasticMaterial",
    slotId: "ModelMarker.051",
    depends: ["ModelMarker.050"],
  },
];
