import { Vector3 } from "three";
import { LegoBlockType } from "../../../Types/LegoBlockType";
import { brick_Specialty_1x2_with_Grill_2877 } from "../../../PartsImports/Brick_Specialty_1x2_with_Grill_2877";
import { brick_Specialty_2x2_Corner_2357 } from "../../../PartsImports/Brick_Specialty_2x2_Corner_2357";
import { plate_1x2_3023 } from "../../../PartsImports/Plate_1x2_3023";
import { plate_Specialty_2x2_Round_with_Axle_Hole_4032 } from "../../../PartsImports/Plate_Specialty_2_x_2_Round_with_Axle_Hole_4032";
import { plate_Specialty_1x2_With_One_Stud_On_Center_3794 } from "../../../PartsImports/Plate_Specialty_1x2_With_One_Stud_On_Center_3794";
import { brick_Specialty_1x2x1_1_3_with_Curved_Top_6091 } from "../../../PartsImports/Brick_Specialty_1x2x1_1_3_with_Curved_Top_6091";
import { round_plate_4073 } from "../../../PartsImports/Round_Plate_4073";

export const locomotiveCabin4564Phase7: LegoBlockType[] = [
  {
    partPath: brick_Specialty_1x2_with_Grill_2877,
    partStartPosition: new Vector3(460, 0, 190),
    partType: "2877",
    materialId: "yellowPLasticMaterial",
    slotId: "ModelMarker.052",
    depends: [],
  },
  {
    partPath: brick_Specialty_1x2_with_Grill_2877,
    partStartPosition: new Vector3(460, 0, 205),
    partType: "2877",
    materialId: "yellowPLasticMaterial",
    slotId: "ModelMarker.053",
    depends: [],
  },
  {
    partPath: brick_Specialty_2x2_Corner_2357,
    partStartPosition: new Vector3(590, 0, 200),
    partType: "2357",
    materialId: "whitePlasticMaterial",
    slotId: "ModelMarker.054",
    depends: [],
  },
  {
    partPath: brick_Specialty_2x2_Corner_2357,
    partStartPosition: new Vector3(590, 0, 225),
    partType: "2357",
    materialId: "whitePlasticMaterial",
    slotId: "ModelMarker.055",
    depends: [],
  },
  {
    partPath: plate_1x2_3023,
    partStartPosition: new Vector3(210, 0, 300),
    partType: "3023",
    materialId: "yellowPLasticMaterial",
    slotId: "ModelMarker.056",
    depends: [],
  },
  {
    partPath: plate_Specialty_2x2_Round_with_Axle_Hole_4032,
    partStartPosition: new Vector3(590, 0, 125),
    partType: "4032",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.057",
    depends: [],
  },
  {
    partPath: plate_Specialty_2x2_Round_with_Axle_Hole_4032,
    partStartPosition: new Vector3(590, 0, 100),
    partType: "4032",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.058",
    depends: [],
  },
  {
    partPath: plate_Specialty_1x2_With_One_Stud_On_Center_3794,
    partStartPosition: new Vector3(370, 0, 190),
    partType: "3794",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.059",
    depends: ["ModelMarker.057"],
  },
  {
    partPath: plate_Specialty_1x2_With_One_Stud_On_Center_3794,
    partStartPosition: new Vector3(370, 0, 205),
    partType: "3794",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.060",
    depends: ["ModelMarker.057"],
  },
  {
    partPath: plate_Specialty_1x2_With_One_Stud_On_Center_3794,
    partStartPosition: new Vector3(370, 0, 220),
    partType: "3794",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.061",
    depends: ["ModelMarker.058"],
  },
  {
    partPath: plate_Specialty_1x2_With_One_Stud_On_Center_3794,
    partStartPosition: new Vector3(370, 0, 235),
    partType: "3794",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.062",
    depends: ["ModelMarker.058"],
  },
  {
    partPath: brick_Specialty_1x2x1_1_3_with_Curved_Top_6091,
    partStartPosition: new Vector3(595, 0, 75),
    partType: "6091",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.063",
    depends: ["ModelMarker.059"],
  },
  {
    partPath: brick_Specialty_1x2x1_1_3_with_Curved_Top_6091,
    partStartPosition: new Vector3(595, 0, 50),
    partType: "6091",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.064",
    depends: ["ModelMarker.060"],
  },
  {
    partPath: brick_Specialty_1x2x1_1_3_with_Curved_Top_6091,
    partStartPosition: new Vector3(595, 0, 25),
    partType: "6091",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.065",
    depends: ["ModelMarker.061"],
  },
  {
    partPath: brick_Specialty_1x2x1_1_3_with_Curved_Top_6091,
    partStartPosition: new Vector3(595, 0, 0),
    partType: "6091",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.066",
    depends: ["ModelMarker.062"],
  },
  {
    partPath: round_plate_4073,
    partStartPosition: new Vector3(390, 0, 220),
    partType: "4073",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.067",
    depends: ["ModelMarker.063"],
  },
  {
    partPath: round_plate_4073,
    partStartPosition: new Vector3(390, 0, 235),
    partType: "4073",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.068",
    depends: ["ModelMarker.064"],
  },
  {
    partPath: round_plate_4073,
    partStartPosition: new Vector3(390, 0, 250),
    partType: "4073",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.069",
    depends: ["ModelMarker.065"],
  },
  {
    partPath: round_plate_4073,
    partStartPosition: new Vector3(390, 0, 265),
    partType: "4073",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.070",
    depends: ["ModelMarker.066"],
  },
  {
    partPath: plate_1x2_3023,
    partStartPosition: new Vector3(185, 0, 315),
    partType: "3023",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.071",
    depends: ["ModelMarker.067", "ModelMarker.068"],
  },
  {
    partPath: plate_1x2_3023,
    partStartPosition: new Vector3(210, 0, 315),
    partType: "3023",
    materialId: "oldGrayPlasticMaterial",
    slotId: "ModelMarker.072",
    depends: ["ModelMarker.069", "ModelMarker.070"],
  },
];
