import { Vector3 } from "three";
import { LegoBlockType } from "../../../Types/LegoBlockType";
import {
  minifig_Accessory_Radio_with_Compact_Handle_3962a,
  minifig_Head_with_Pointed_Moustache_Pattern_3626bp03,
  minifig_Headgear_Construction_Helmet_3833,
  minifig_Hips_and_Legs_970c00,
  minifig_Torso_Train_Red_Vest_Pattern_973px8c01,
  tile_1x2_with_Telemetry_Panel_Pattern_3069px2,
  train_Wheel_Small_2927,
} from "../set4552PartsImports";

export const car4552Phase10: LegoBlockType[] = [
  {
    partPath: tile_1x2_with_Telemetry_Panel_Pattern_3069px2,
    partStartPosition: new Vector3(265, 0, 180),
    partType: "3069px2",
    slotId: "ModelMarker.030",
    depends: [],
  },
  {
    partPath: train_Wheel_Small_2927,
    partStartPosition: new Vector3(100, 0, 190),
    partType: "2927",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.031",
    depends: [],
  },
  {
    partPath: train_Wheel_Small_2927,
    partStartPosition: new Vector3(100, 0, 210),
    partType: "2927",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.032",
    depends: [],
  },
  {
    partPath: train_Wheel_Small_2927,
    partStartPosition: new Vector3(120, 0, 190),
    partType: "2927",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.033",
    depends: [],
  },
  {
    partPath: train_Wheel_Small_2927,
    partStartPosition: new Vector3(120, 0, 210),
    partType: "2927",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.034",
    depends: [],
  },
  {
    partPath: minifig_Hips_and_Legs_970c00,
    partStartPosition: new Vector3(420, 0, 210),
    partType: "970c00",
    materialId: "bluePlasticMaterial",
    multipart: true,
    propagateMainMaterialToChildren: true,
    slotId: "ModelMarker.035",
    depends: [],
  },
  {
    partPath: minifig_Torso_Train_Red_Vest_Pattern_973px8c01,
    partStartPosition: new Vector3(420, 0, 190),
    partType: "973px8c01",
    multipart: true,
    noAutomaticMoveToGroundLevel: true,
    slotId: "ModelMarker.036",
    depends: ["ModelMarker.035"],
  },
  {
    partPath: minifig_Head_with_Pointed_Moustache_Pattern_3626bp03,
    partStartPosition: new Vector3(420, 0, 165),
    partType: "3626bp03",
    slotId: "ModelMarker.037",
    depends: ["ModelMarker.036"],
  },
  {
    partPath: minifig_Headgear_Construction_Helmet_3833,
    partStartPosition: new Vector3(420, 0, 140),
    partType: "3833",
    materialId: "whitePlasticMaterial",
    slotId: "ModelMarker.038",
    depends: ["ModelMarker.037"],
  },
  {
    partPath: minifig_Accessory_Radio_with_Compact_Handle_3962a,
    partStartPosition: new Vector3(-260, 0, 235),
    partType: "3962a",
    materialId: "darkGrayPlasticMaterial",
    slotId: "ModelMarker.039",
    depends: ["ModelMarker.036"],
  },
];
