import { Vector3 } from "three";
import { LegoBlockType } from "../../../Types/LegoBlockType";
import {
  plate_1x6_3666,
  plate_2_x_2_3022,
  slope_Brick_Inverted_3665,
} from "../Set7722V1PartsImports";

export const steamLocomotive7722PlatformCarPhase3: LegoBlockType[] = [
  {
    partPath: plate_1x6_3666,
    partStartPosition: new Vector3(0, 0, 310),
    partType: "3666",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.018",
    depends: [],
  },
  {
    partPath: plate_1x6_3666,
    partStartPosition: new Vector3(0, 0, 325),
    partType: "3666",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.019",
    depends: [],
  },
  {
    partPath: plate_2_x_2_3022,
    partStartPosition: new Vector3(-265, 0, 160),
    partType: "3022",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.028",
    depends: [],
  },
  {
    partPath: plate_2_x_2_3022,
    partStartPosition: new Vector3(-290, 0, 160),
    partType: "3022",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.029",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_3665,
    partStartPosition: new Vector3(450, 0, 50),
    partType: "3665",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.020",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_3665,
    partStartPosition: new Vector3(470, 0, 50),
    partType: "3665",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.021",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_3665,
    partStartPosition: new Vector3(490, 0, 50),
    partType: "3665",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.022",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_3665,
    partStartPosition: new Vector3(510, 0, 50),
    partType: "3665",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.023",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_3665,
    partStartPosition: new Vector3(450, 0, 75),
    partType: "3665",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.024",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_3665,
    partStartPosition: new Vector3(470, 0, 75),
    partType: "3665",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.025",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_3665,
    partStartPosition: new Vector3(490, 0, 75),
    partType: "3665",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.026",
    depends: [],
  },
  {
    partPath: slope_Brick_Inverted_3665,
    partStartPosition: new Vector3(510, 0, 75),
    partType: "3665",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.027",
    depends: [],
  },
];
