import Hinge_Hook_Base_Slider_Arm_with_Three_Finger_And_Rubber_2650w_model from "../assets/Blocks/Hinge_Hook_Base_Slider_Arm_with_Three_Finger_And_Rubber_2650w/Hinge_Hook_Base_Slider_Arm_with_Three_Finger_And_Rubber_2650w.glb";
export const hinge_Hook_Base_Slider_Arm_with_Three_Finger_And_Rubber_2650w =
  Hinge_Hook_Base_Slider_Arm_with_Three_Finger_And_Rubber_2650w_model;
