import Hinge_Train_Gate_2x4_With_White_Train_Logo_2873_model from "../assets/Blocks/Hinge_Train_Gate_2x4_With_White_Train_Logo_2873/Hinge_Train_Gate_2x4_With_White_Train_Logo_2873.glb";

export const hinge_Train_Gate_2x4_With_White_Train_Logo_2873 =
  Hinge_Train_Gate_2x4_With_White_Train_Logo_2873_model;
