import { Vector3 } from "three";
import { LegoBlockType } from "../../../Types/LegoBlockType";
import {
  brick_1x6_3009,
  brick_4070,
  electric_Wire_766c28,
  round_Plate_4073,
} from "../Set7722V1PartsImports";

export const steamLocomotive7722LocomotiveModelPhase5: LegoBlockType[] = [
  {
    partPath: brick_1x6_3009,
    partStartPosition: new Vector3(180, 0, 115),
    partType: "3009",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.033",
    depends: [],
  },
  {
    partPath: brick_1x6_3009,
    partStartPosition: new Vector3(180, 0, 130),
    partType: "3009",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.034",
    depends: [],
  },
  {
    partPath: brick_4070,
    partStartPosition: new Vector3(180, 0, 85),
    partType: "4070",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.028",
    depends: [],
  },
  {
    partPath: brick_4070,
    partStartPosition: new Vector3(195, 0, 85),
    partType: "4070",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.027",
    depends: [],
  },
  {
    partPath: brick_4070,
    partStartPosition: new Vector3(180, 0, 100),
    partType: "4070",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.026",
    depends: [],
  },
  {
    partPath: brick_4070,
    partStartPosition: new Vector3(195, 0, 100),
    partType: "4070",
    materialId: "blackPlasticMaterial",
    slotId: "ModelMarker.025",
    depends: [],
  },
  {
    partPath: round_Plate_4073,
    partStartPosition: new Vector3(195, 0, 70),
    partType: "4073",
    materialId: "whiteTransparentMaterial",
    slotId: "ModelMarker.031",
    depends: ["ModelMarker.028"],
  },
  {
    partPath: round_Plate_4073,
    partStartPosition: new Vector3(195, 0, 55),
    partType: "4073",
    materialId: "whiteTransparentMaterial",
    slotId: "ModelMarker.032",
    depends: ["ModelMarker.027"],
  },
  {
    partPath: round_Plate_4073,
    partStartPosition: new Vector3(180, 0, 55),
    partType: "4073",
    materialId: "redTransparentMaterial",
    slotId: "ModelMarker.029",
    depends: ["ModelMarker.026"],
  },
  {
    partPath: round_Plate_4073,
    partStartPosition: new Vector3(180, 0, 70),
    partType: "4073",
    materialId: "redTransparentMaterial",
    slotId: "ModelMarker.030",
    depends: ["ModelMarker.025"],
  },
  {
    partPath: electric_Wire_766c28,
    partStartPosition: new Vector3(180, 0, -20),
    partType: "766c28",
    canNotBeRotated: true,
    noAutomaticMoveToGroundLevel: true,
    slotId: "ModelMarker.024",
    depends: [],
  },
];
